CREATE DATABASE bdPartido
USE bdPartido

SELECT * FROM dbo.tbFiliado

-- 1)
SELECT NOME_DO_FILIADO FROM dbo.tbFiliado
WHERE NOME_DO_FILIADO LIKE 'ANTONIO%'

-- 2)
SELECT NOME_DO_FILIADO FROM dbo.tbFiliado
WHERE NOME_DO_FILIADO LIKE '%SEBASTIAO'

-- 3)
SELECT NOME_DO_FILIADO FROM dbo.tbFiliado
WHERE NOME_DO_FILIADO LIKE 'OS%'

-- 4)
SELECT NOME_DO_FILIADO, NOME_DO_MUNICIPIO FROM dbo.tbFiliado
WHERE NOME_DO_MUNICIPIO LIKE 'SÃO FELIX'

-- 5)
SELECT NOME_DO_FILIADO, NOME_DO_MUNICIPIO FROM dbo.tbFiliado
WHERE NOME_DO_MUNICIPIO LIKE 'INHAMBUPE'

-- 6)
SELECT NOME_DO_MUNICIPIO FROM dbo.tbFiliado
WHERE NOME_DO_MUNICIPIO LIKE 'SANTA%'

-- 7)
SELECT NOME_DO_MUNICIPIO FROM dbo.tbFiliado
WHERE NOME_DO_MUNICIPIO LIKE 'E%'

-- 8)
SELECT NOME_DO_MUNICIPIO FROM dbo.tbFiliado
WHERE NOME_DO_MUNICIPIO LIKE '%CRUZ%'

-- 9)
SELECT NOME_DO_MUNICIPIO FROM dbo.tbFiliado
WHERE NOME_DO_MUNICIPIO LIKE '%DE%'

-- 10)
SELECT NOME_DO_FILIADO, CONVERT(VARCHAR(10), DATA_DA_FILIACAO,103) FROM dbo.tbFiliado
WHERE DATA_DA_FILIACAO BETWEEN '01-01-1990' AND '01-01-2000'

-- 11)
SELECT NOME_DO_FILIADO, CONVERT(VARCHAR(10), DATA_DA_FILIACAO,103) FROM dbo.tbFiliado
WHERE DATA_DA_FILIACAO BETWEEN '02/01/2010' AND '01/03/2010'

-- 12)
SELECT NOME_DO_FILIADO, CONVERT(VARCHAR(10), DATA_DA_FILIACAO, 103) AS 'Filiados cadastrados no 2º Semestre de 2007' FROM dbo.tbFiliado
WHERE DATA_DA_FILIACAO BETWEEN '01-07-2007' AND '01-12-2007'

-- 13)
SELECT NOME_DO_FILIADO, SITUACAO_DO_REGISTRO FROM dbo.tbFiliado
WHERE SITUACAO_DO_REGISTRO LIKE 'REGULAR'

-- 14)
SELECT NOME_DO_FILIADO, ZONA_ELEITORAL FROM dbo.tbFiliado
WHERE ZONA_ELEITORAL LIKE '203'

-- 15)
SELECT NOME_DO_FILIADO, ZONA_ELEITORAL FROM dbo.tbFiliado
WHERE ZONA_ELEITORAL LIKE '180'

-- 16)
SELECT NOME_DO_FILIADO, ZONA_ELEITORAL FROM dbo.tbFiliado
WHERE ZONA_ELEITORAL LIKE '199'

-- 17)
SELECT MAX(ZONA_ELEITORAL)AS 'Maior número da Zona Eleitoral' FROM dbo.tbFiliado

-- 18)
SELECT MIN(ZONA_ELEITORAL)AS 'Menor número da Zona Eleitoral' FROM dbo.tbFiliado

-- 19)
UPDATE dbo.tbFiliado
SET SIGLA_DO_PARTIDO = 'PT'
WHERE CODIGO_DO_MUNICIPIO = 36471

-- 20)
UPDATE dbo.tbFiliado 
SET SIGLA_DO_PARTIDO = 'PMDB'
WHERE CODIGO_DO_MUNICIPIO = 38490

-- 21)
UPDATE dbo.tbFiliado
SET SIGLA_DO_PARTIDO = 'PC'
WHERE NOME_DO_MUNICIPIO = 'SANTANÓPOLIS'

-- 22)
UPDATE dbo.tbFiliado
SET SIGLA_DO_PARTIDO = 'PV'
WHERE SIGLA_DO_PARTIDO = 'PTC'

UPDATE dbo.tbFiliado
SET SIGLA_DO_PARTIDO = 'PV'
WHERE NOME_DO_MUNICIPIO = 'SÃO FÉLIX'

-- 23) 
UPDATE dbo.tbFiliado
SET SIGLA_DO_PARTIDO = 'PSDB'
WHERE SIGLA_DO_PARTIDO = 'PTC'

UPDATE dbo.tbFiliado
SET SIGLA_DO_PARTIDO = 'PSDB'
WHERE NOME_DO_MUNICIPIO = 'ENCRUZILHADA'

-- 24)
UPDATE dbo.tbFiliado 
SET NOME_DO_FILIADO = 'JORGE LUIS MAGALHÃES DOS SANTOS'
WHERE NUMERO_DA_INSCRICAO = 32356

-- 25)
UPDATE dbo.tbFiliado 
SET NOME_DO_FILIADO = 'RENATA XAVIER RODRIGUES'
WHERE NUMERO_DA_INSCRICAO = 32377

-- 26)
UPDATE dbo.tbFiliado 
SET NOME_DO_FILIADO = 'NOEL LEITE DA SILVA'
WHERE NUMERO_DA_INSCRICAO = 32373

-- 27)
UPDATE dbo.tbFiliado
SET SITUACAO_DO_REGISTRO = 'REGULAR'
WHERE NOME_DO_FILIADO = 'JOSIENE ANDRADE DE SOUZA'

-- 28)
UPDATE dbo.tbFiliado
SET SITUACAO_DO_REGISTRO = 'REGULAR'
WHERE NOME_DO_FILIADO = 'ELIEL ALMEIDA SILVA'

-- 29)
UPDATE dbo.tbFiliado
SET SITUACAO_DO_REGISTRO = 'DESFILIADO'
WHERE NOME_DO_FILIADO = 'ALINE DE SOUZA'

-- 30)
ALTER TABLE dbo.tbFiliado ADD SEXO CHAR